=== ppnnh/STP-4-sem/lab03/files/validation.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://msiter.ru" xmlns="http://msiter.ru" elementFormDefault="qualified">

    <xs:element name="Container">
    <xs:complexType>
    <xs:sequence>
        <xs:element name="CardList">
        <xs:complexType>
        <xs:sequence>
            <xs:element name="Card" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                <xs:sequence>
                    <xs:element name="Number" type="xs:int" />
                    <xs:element name="Balance" type="xs:int" />
                </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
    </xs:sequence>
</xs:complexType>
</xs:element>

</xs:schema>

=== ppnnh/STP-4-sem/lab03/files/cardlist.xml
<?xml version="1.0" encoding="utf-8"?>
<Container xmlns="http://msiter.ru"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://msiter.ru validation.xsd">
    
    <CardList>
        <Card>
            <Number>100458</Name>
            <Balance>58634</Balance>
        </Card>
        <Card>
            <Number>100352</Number>
            <Balance>58634</Balance>
        </Card>
        <Card>
            <Number>100263</Number>
            <Balance>58634</Balance>
        </Card>
        <Card>
            <Number>100522</Number>
            <Balance>58634</Balance>
        </Card>
    </CardList>
</Container>
